name: Real Gmail Account Creator

on:
  workflow_dispatch:
    inputs:
      start_index:
        description: 'Start index for account creation'
        required: false
        default: '1'
        type: string
      end_index:
        description: 'End index for account creation'
        required: false
        default: '5'
        type: string

jobs:
  create-real-gmail-accounts:
    name: Create Real Gmail Accounts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        
    - name: Run Real Gmail Creator
      env:
        START_INDEX: ${{ inputs.start_index }}
        END_INDEX: ${{ inputs.end_index }}
      run: |
        python real_gmail_creator.py
        
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: real-gmail-accounts-results
        path: |
          real_gmail_accounts.csv
          real_gmail_accounts.json
          real_gmail_creator.log
        retention-days: 7
        
    - name: Display summary
      run: |
        echo "🎉 Real Gmail Account Creation Completed!"
        echo "Check artifacts for detailed results"
        if [ -f real_gmail_accounts.csv ]; then
          echo "Results summary:"
          tail -n +2 real_gmail_accounts.csv | cut -d',' -f6 | sort | uniq -c
        fi
